# Generated by Django 5.1.6 on 2025-02-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_deliveryguy_phone_number_seller_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
