# Generated by Django 5.1.6 on 2025-02-16 05:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_order_delivery_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
